# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2febb686c474a0eb2713b16dc13c3f7cae90f9d399f8b3ad56d559c1255cd66c0b32c84bc10151f64aff7bf78c992d5643b0a1e30fd4a201ad27ac7f65bf8778

test:
  secret_key_base: 67fa86a6736767193aee5795a0746028d81e354f7eeefdc5604ce88e23918f6a574dc6b967d0d6403b180a83444d06ba23dac4d0bb6b6e037f6e0136e5991249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
